language: node_js
node_js: '8.0.0'
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fakeroot wine
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file_glob: true
  file: "./dist/*"
  on:
    repo: etaletai13/Atlayo
    tags: true
