os: osx
language: node_js
node_js: '8.0.0'
before_install:
  - brew update 
  - brew install fakeroot wine
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file_glob: true
  file: "./dist/*.dmg"
  on:
    branch:
      only: osx
    repo: etaletai13/Atlayo
    tags: true
